FROM node:alpine as builder

WORKDIR "/app"

COPY ./package.json ./

RUN npm install 
# after copy all files to current work dir
COPY ./ ./

# Default command
RUN npm run build

FROM nginx

# copy from build phase from app/build dir to nginx

COPY --from=builder /app/build /usr/share/nginx/html 
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
# start nginx it will done automatically